import { TemplatesProvider } from '@/components/context/templates';
import Loading from '@/components/elements/loading';
import TemplateService from '@/services/template.service';
import { Metadata } from 'next';
import { Suspense } from 'react';

export const metadata: Metadata = {
	title: 'Broadcasts • Wautopilot',
};
const templates = [
	{
		id: '499259179221320',
		name: 'task_wautopilot_reminder',
		status: 'APPROVED',
		category: 'UTILITY',
		components: [
			{
				type: 'BODY',
				text: 'Dear {{1}},\n\nThis is a friendly reminder about your upcoming task on Wautopilot. Please review the details below and ensure you complete it on time.\n\n*Remarks* - {{2}}\n\nHere are the task details:\n*Category* - {{3}}\n*Task* - {{4}}\n*Due Date* - {{5}}\n*Priority* - {{6}}',
				example: {
					body_text: [
						['Prashant', 'Completed', 'Update_ALL', 'Status Updates', '02nd Aug', 'High'],
					],
				},
			},
			{ type: 'FOOTER', text: 'This is a notification generated by task.wautopilot.com' },
			{
				type: 'BUTTONS',
				buttons: [
					{
						type: 'URL',
						text: 'Open Task',
						url: 'https://task.wautopilot.com/organizations{{1}}',
						example: ['task-id-1'],
					},
				],
			},
		],
	},
	{
		id: '853831216850857',
		name: 'pv_linkedin_facebook_links_message',
		status: 'APPROVED',
		category: 'MARKETING',
		components: [
			{
				type: 'HEADER',
				format: 'IMAGE',
				example: {
					header_handle: [
						'https://scontent.whatsapp.net/v/t61.29466-34/459095902_853831223517523_6617838058198772727_n.png?ccb=1-7&_nc_sid=8b1bef&_nc_ohc=LfHo0xFbbewQ7kNvgGdXo-E&_nc_ht=scontent.whatsapp.net&edm=AH51TzQEAAAA&_nc_gid=AWzubpBdy7fAb4f6NmXZzx6&oh=01_Q5AaIFgMXnugtcpSVP2cMprevRCy_xIiyrPTMu-cT4yr-j30&oe=6729E0D8',
					],
				},
			},
			{
				type: 'BODY',
				text: 'Lets connect on Social Media also.\n\nPlease click on the button below to connect.\n\n👇👇👇👇',
			},
			{
				type: 'BUTTONS',
				buttons: [
					{
						type: 'URL',
						text: 'Linkedin',
						url: 'https://www.linkedin.com/in/coachprashantvarma/',
					},
					{ type: 'URL', text: 'Facebook', url: 'https://www.facebook.com/prashaant.varma' },
				],
			},
		],
	},
	{
		id: '406861508512098',
		name: 'task_wautopilot_status_update',
		status: 'APPROVED',
		category: 'UTILITY',
		components: [
			{
				type: 'BODY',
				text: 'Dear {{1}},\n\n{{2}} has updated the status of the task to *{{3}}*.\n\n*Remarks* - {{4}}\n\nHere are the task details:\n*Category* - {{5}}\n*Task* - {{6}}\n*Due Date* - {{7}}\n*Priority* - {{8}}',
				example: {
					body_text: [
						[
							'Prashant',
							'Prashant',
							'In Progress',
							'Working on this task',
							'Accounts',
							'Task 1',
							'05-Jul-24 10:00 AM',
							'High',
						],
					],
				},
			},
			{ type: 'FOOTER', text: 'This is a notification generated by task.wautopilot.com' },
			{
				type: 'BUTTONS',
				buttons: [
					{
						type: 'URL',
						text: 'Open Task',
						url: 'https://task.wautopilot.com/organizations{{1}}',
						example: ['task-id-1'],
					},
				],
			},
		],
	},
	{
		id: '703008418565758',
		name: 'bni_first_message',
		status: 'APPROVED',
		category: 'MARKETING',
		components: [
			{
				type: 'BODY',
				text: '*Good Morning BNI {{1}} Ji,*\n\nThis is Prashant Varma from BNI Athena, Delhi South.\n\nSaw your profile on BNIConnect sometime back.\n\nWhat would be the best way to communicate if I find some relevant referral for you. \n👇👇👇👇👇',
				example: { body_text: [['Name']] },
			},
			{
				type: 'BUTTONS',
				buttons: [
					{ type: 'QUICK_REPLY', text: 'Whatsappp' },
					{ type: 'QUICK_REPLY', text: 'Calll' },
					{ type: 'QUICK_REPLY', text: 'SMS' },
				],
			},
		],
	},
	{
		id: '1523000151653254',
		name: '234',
		status: 'APPROVED',
		category: 'MARKETING',
		components: [{ type: 'BODY', text: '234' }],
	},
	{
		id: '8000423059997120',
		name: 'task_wautopilot_status_create',
		status: 'APPROVED',
		category: 'UTILITY',
		components: [
			{
				type: 'BODY',
				text: 'Dear {{1}},\n\n{{2}} has assigned a task with status *{{3}}*.\n\n*Remarks* - {{4}}\n\nHere are the task details:\n*Category* - {{5}}\n*Task* - {{6}}\n*Due Date* - {{7}}\n*Priority* - {{8}}',
				example: {
					body_text: [
						[
							'Prashant',
							'Prashant',
							'In Progress',
							'Working on this task',
							'Accounts',
							'Task 1',
							'05-Jul-24 10:00 AM',
							'High',
						],
					],
				},
			},
			{ type: 'FOOTER', text: 'This is a notification generated by task.wautopilot.com' },
			{
				type: 'BUTTONS',
				buttons: [
					{
						type: 'URL',
						text: 'Open Task',
						url: 'https://task.wautopilot.com/organizations{{1}}',
						example: ['task-id-1'],
					},
				],
			},
		],
	},
	{
		id: '1037848077881368',
		name: 'referral_partner_survey_digital_marketing',
		status: 'APPROVED',
		category: 'MARKETING',
		components: [
			{
				type: 'BODY',
				text: 'Good Morning BNI {{1}} Ji,\n\nThis is Prashant Varma from BNI Athena, Delhi South.\n\nGot your reference sometime back from a BNI Group.\n\nI recieved an enquiry for Digital Marketing Services in {{2}}\n\nDo you do Digital Marketing ?\n\nKindly confirm 👇',
				example: { body_text: [['First Name', 'City']] },
			},
			{ type: 'BUTTONS', buttons: [{ type: 'QUICK_REPLY', text: 'I Do Digital Marketing' }] },
		],
	},
	{
		id: '1547477319537802',
		name: 'referral_partner_survey',
		status: 'APPROVED',
		category: 'MARKETING',
		components: [
			{
				type: 'BODY',
				text: 'Good Morning BNI {{1}} {{2}} {{3}},\n\nThis is Prashant Varma from BNI Athena, Delhi South.\n\nSaw your profile some time back on BNI Connect.\n\nI recieved an enquiry for Digital Marketing Services in {{4}}\n\nDo you do Digital Marketing.  \n\nKindly confirm 👇',
				example: { body_text: [['First Name', 'Middle Name', 'Last Name', 'City Name']] },
			},
			{ type: 'BUTTONS', buttons: [{ type: 'QUICK_REPLY', text: 'I Do Digital Marketing' }] },
		],
	},
	{
		id: '1030943261773894',
		name: 'utility_test_message',
		status: 'APPROVED',
		category: 'UTILITY',
		components: [
			{
				type: 'BODY',
				text: 'You received a new notification, {{1}}',
				example: { body_text: [['Name']] },
			},
			{
				type: 'BUTTONS',
				buttons: [
					{ type: 'QUICK_REPLY', text: 'Yes' },
					{ type: 'QUICK_REPLY', text: 'No' },
				],
			},
		],
	},
	{
		id: '1747181659355758',
		name: 'prashant_real_estate_consultant',
		status: 'APPROVED',
		category: 'MARKETING',
		components: [
			{ type: 'HEADER', format: 'TEXT', text: 'Are you a Real Estate Consultant' },
			{
				type: 'BODY',
				text: 'Are you a {{1}} {{2}} Based Real Estate Consultant ?',
				example: { body_text: [['South', 'Delhi']] },
			},
			{
				type: 'BUTTONS',
				buttons: [
					{ type: 'QUICK_REPLY', text: 'Yes I am in South Delhi' },
					{ type: 'QUICK_REPLY', text: 'No I am Not in South Delh' },
				],
			},
		],
	},
	{
		id: '3369298416697493',
		name: 'propmatch_plot_requirement',
		status: 'APPROVED',
		category: 'MARKETING',
		components: [
			{
				type: 'BODY',
				text: 'Hi ,\n\nLooking for a plot or kothi in the following colony for a client.\n\nColony - {{1}} \nSize - {{2}}\n\nKindly confirm if you have something similar available',
				example: {
					body_text: [['Hauz Khas / Green Park / Safdarjung Enclave', '200 - 300 Sqyd']],
				},
			},
			{ type: 'FOOTER', text: 'www.propmatch.in' },
			{
				type: 'BUTTONS',
				buttons: [
					{ type: 'QUICK_REPLY', text: 'Plot Available 00001' },
					{ type: 'QUICK_REPLY', text: 'Not Available' },
				],
			},
		],
	},
	{
		id: '823852523056553',
		name: 'task_wautopilot_today_overview',
		status: 'APPROVED',
		category: 'UTILITY',
		components: [
			{
				type: 'BODY',
				text: 'Dear {{1}},\n\n{{2}} has updated the status of the task to *{{3}}*.\n\n*Remarks* - {{4}}\n\nHere are the task details:\n*Category* - {{5}}\n*Task* - {{6}}\n*Due Date* - {{7}}\n*Priority* - {{8}}',
				example: {
					body_text: [
						[
							'Prashant',
							'Prashant',
							'In Progress',
							'Working on this task',
							'Accounts',
							'Task 1',
							'05-Jul-24 10:00 AM',
							'High',
						],
					],
				},
			},
			{ type: 'FOOTER', text: 'This is a notification generated by task.wautopilot.com' },
			{
				type: 'BUTTONS',
				buttons: [
					{
						type: 'URL',
						text: 'Open Task',
						url: 'https://task.wautopilot.com/organizations{{1}}',
						example: ['task-id-1'],
					},
				],
			},
		],
	},
	{
		id: '950356093128522',
		name: 'lead_notification',
		status: 'APPROVED',
		category: 'MARKETING',
		components: [
			{ type: 'HEADER', format: 'TEXT', text: 'Notification from Save My V Card' },
			{
				type: 'BODY',
				text: 'Hi {{1}},\n\nThe following person has downloaded your contact card.\n\n*Name*: {{2}}\n*Contact Number*: {{3}}\n*Message Received*:  {{4}}\n\nRegards,\nSaveMyVCard',
				example: {
					body_text: [['Prashant', 'Manzar', '919718793635', 'Contact Card for Prashant Varma']],
				},
			},
			{ type: 'BUTTONS', buttons: [{ type: 'QUICK_REPLY', text: 'Get Contact Card' }] },
		],
	},
	{
		id: '7846637745396362',
		name: 'send_callback_button',
		status: 'APPROVED',
		category: 'MARKETING',
		components: [
			{ type: 'HEADER', format: 'TEXT', text: 'CALL BACK BUTTON TESTING' },
			{ type: 'BODY', text: 'Hi,\n\nThis is just to check the callback button on whatsapp.' },
			{ type: 'BUTTONS', buttons: [{ type: 'VOICE_CALL', text: 'Get in touch' }] },
		],
	},
	{
		id: '377289165329696',
		name: 'whatsapp_calling_butoon_testing',
		status: 'APPROVED',
		category: 'MARKETING',
		components: [
			{ type: 'BODY', text: 'whatsapp call testing from button' },
			{ type: 'BUTTONS', buttons: [{ type: 'VOICE_CALL', text: 'Whatsapp Call' }] },
		],
	},
	{
		id: '750640087231581',
		name: 'bni_requirement',
		status: 'APPROVED',
		category: 'MARKETING',
		components: [
			{
				type: 'BODY',
				text: 'Hi {{1}} ,\n\n{{2}}.\n\nKindly let me know if you deal in it or know another BNI member. \n\nRegards,\nPrashant Varma',
				example: { body_text: [['Name', 'Specific Ask']] },
			},
			{
				type: 'BUTTONS',
				buttons: [
					{ type: 'QUICK_REPLY', text: 'I deal in this' },
					{ type: 'QUICK_REPLY', text: "I don't deal in this" },
				],
			},
		],
	},
	{
		id: '780197390878909',
		name: 'bni_bniconnect_connection_request',
		status: 'APPROVED',
		category: 'MARKETING',
		components: [
			{
				type: 'BODY',
				text: '*Good Morning BNI* {{1}} ,\n\nSent you request on your BNIConnect Profile few days back , please accept it . \n\nAlso wanted to know the best way to stay connected with you .\n\nRegards,\nName - Prashant Varma\nCategory - Performance Coach\nUSP - Helping Businesses grow with the power of Whatsapp\nChapter - BNI Athena\nRegion - Delhi South',
				example: { body_text: [['Name']] },
			},
			{
				type: 'BUTTONS',
				buttons: [
					{ type: 'QUICK_REPLY', text: 'Whatsapp' },
					{ type: 'QUICK_REPLY', text: 'Connect on Linkedin' },
					{ type: 'QUICK_REPLY', text: 'I have left BNI' },
				],
			},
		],
	},
	{
		id: '1144349926608624',
		name: 'bni_group_joining_message1',
		status: 'APPROVED',
		category: 'MARKETING',
		components: [
			{
				type: 'BODY',
				text: 'Hi {{1}} ,\n\nBased on your request here is the group link based on your business address listed.\n\n{{2}}\n\nIf the above address is correct.\n\nPlease join Nearby Business Network Group  {{3}}',
				example: { body_text: [['Name', 'address', 'link']] },
			},
		],
	},
	{
		id: '724318373199783',
		name: 'mar_bni_pincode_message',
		status: 'APPROVED',
		category: 'MARKETING',
		components: [
			{
				type: 'BODY',
				text: 'Good Morning BNI {{1}} ,\n\nWhile going through BNIConnect a few days ago, I saw your office is in {{2}} .\n\nI visit {{2}} regularly, and would like to do 1-2-1 when I visit next time .\n\nPlease share your *Google Location of your Business* .\n\nRegards,\nPrashant Varma\nPerformance Coach\nBNI Athena, Delhi South',
				example: { body_text: [['Name', 'Colony']] },
			},
			{
				type: 'BUTTONS',
				buttons: [
					{ type: 'QUICK_REPLY', text: "Let's Connect" },
					{ type: 'QUICK_REPLY', text: 'I will connect later' },
				],
			},
		],
	},
	{
		id: '7228429823920445',
		name: 'thank_you_bni_message_vcard',
		status: 'APPROVED',
		category: 'MARKETING',
		components: [
			{
				type: 'BODY',
				text: 'Thank you for your response.\n\n*Please save my contact Card* for future reference.',
			},
		],
	},
	{
		id: '943212587422720',
		name: 'mar_bni_community1',
		status: 'APPROVED',
		category: 'MARKETING',
		components: [
			{ type: 'BODY', text: 'https://chat.whatsapp.com/DOcFgvTpAyHGuTKOAmvXlg' },
			{
				type: 'BUTTONS',
				buttons: [
					{
						type: 'URL',
						text: 'Delhi Nearby Business',
						url: 'https://bit.ly/BNI_Whatsapp_Community_Delhi',
					},
				],
			},
		],
	},
	{
		id: '3174156109386348',
		name: 'mar_after_exhibiion_message',
		status: 'APPROVED',
		category: 'MARKETING',
		components: [
			{
				type: 'BODY',
				text: 'Hello {{1}} ,\n\nDid you attend {{2}} ?\n\nRegards,\nPrashant Varma',
				example: { body_text: [['Name', 'Exhibition']] },
			},
			{ type: 'FOOTER', text: 'Powered by : wa.savemyvcard.com' },
		],
	},
	{
		id: '965895858578875',
		name: 'mar_exhibition_lead_generation',
		status: 'APPROVED',
		category: 'MARKETING',
		components: [
			{
				type: 'BODY',
				text: 'Hi  {{1}},\n\nAre you attending {{2}} ?\n\nKindly share your Stall / booth details and if possible google location.\n\nWill meet you if I get the opportunity.\n\nRegards,\nPrashant Varma',
				example: { body_text: [['Name', 'Exhibition']] },
			},
			{ type: 'FOOTER', text: 'www.SaveMyVCard.com' },
		],
	},
	{
		id: '731482685631167',
		name: 'naukri_first_message',
		status: 'APPROVED',
		category: 'MARKETING',
		components: [
			{
				type: 'BODY',
				text: 'Hi *{{1}}*,\n\nWe got your details from *{{2}}*.\n\nWe found some jobs nearby your residence for *{{3}}*.\n\nIf Interested, kindly click on *Yes Nearby Naukri*\n\nRegards,\n*Team Nearby Naukri*',
				example: { body_text: [['Candidate Name', 'Job Portal Name', 'Job Requirement Title']] },
			},
			{
				type: 'BUTTONS',
				buttons: [
					{ type: 'QUICK_REPLY', text: 'Yes Nearby Naukri' },
					{ type: 'QUICK_REPLY', text: "No , I don't want Job" },
				],
			},
		],
	},
	{
		id: '914676950062961',
		name: 'get_your_vcard',
		status: 'APPROVED',
		category: 'MARKETING',
		components: [
			{
				type: 'BODY',
				text: 'Do you want to *Increase your sales* using *Save My V Card* automated V Card sharing on whatsapp ?',
			},
			{
				type: 'BUTTONS',
				buttons: [{ type: 'URL', text: 'Yes', url: 'https://savemyvcard.in/' }],
			},
		],
	},
]

export default async function Layout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	// const templates = (await TemplateService.listTemplates())!;

	return (
		<Suspense fallback={<Loading />}>
			<section>
				<TemplatesProvider data={templates!}>{children}</TemplatesProvider>
			</section>
		</Suspense>
	);
}
