import { TemplatesProvider } from '@/components/context/templates';
import Loading from '@/components/elements/loading';
import TemplateService from '@/services/template.service';
import { Metadata } from 'next';
import { Suspense } from 'react';

export const metadata: Metadata = {
	title: 'Broadcasts • Wautopilot',
};
// const templates = [
// 	{
// 		_id: '1037848077881368',
// 		name: 'referral_partner_survey_digital_marketing',
// 		status: 'APPROVED',
// 		category: 'MARKETING',
// 		body: {
// 			text: 'Good Morning BNI {{1}} Ji,\n\nThis is Prashant Varma from BNI Athena, Delhi South.\n\nGot your reference sometime back from a BNI Group.\n\nI recieved an enquiry for Digital Marketing Services in {{2}}\n\nDo you do Digital Marketing ?\n\nKindly confirm 👇',
// 			example: ['First Name', 'City'],
// 		},
// 		buttons: [{ type: 'QUICK_REPLY', text: 'I Do Digital Marketing' }],
// 	},
// 	{
// 		_id: '8000423059997120',
// 		name: 'task_wautopilot_status_create',
// 		status: 'APPROVED',
// 		category: 'UTILITY',
// 		body: {
// 			text: 'Dear {{1}},\n\n{{2}} has assigned a task with status *{{3}}*.\n\n*Remarks* - {{4}}\n\nHere are the task details:\n*Category* - {{5}}\n*Task* - {{6}}\n*Due Date* - {{7}}\n*Priority* - {{8}}',
// 			example: [
// 				'Prashant',
// 				'Prashant',
// 				'In Progress',
// 				'Working on this task',
// 				'Accounts',
// 				'Task 1',
// 				'05-Jul-24 10:00 AM',
// 				'High',
// 			],
// 		},
// 		footer: { text: 'This is a notification generated by task.wautopilot.com' },
// 		buttons: [
// 			{
// 				type: 'URL',
// 				text: 'Open Task',
// 				url: 'https://task.wautopilot.com/organizations{{1}}',
// 				example: ['task-id-1'],
// 			},
// 		],
// 	},
// 	{
// 		_id: '406861508512098',
// 		name: 'task_wautopilot_status_update',
// 		status: 'APPROVED',
// 		category: 'UTILITY',
// 		body: {
// 			text: 'Dear {{1}},\n\n{{2}} has updated the status of the task to *{{3}}*.\n\n*Remarks* - {{4}}\n\nHere are the task details:\n*Category* - {{5}}\n*Task* - {{6}}\n*Due Date* - {{7}}\n*Priority* - {{8}}',
// 			example: [
// 				'Prashant',
// 				'Prashant',
// 				'In Progress',
// 				'Working on this task',
// 				'Accounts',
// 				'Task 1',
// 				'05-Jul-24 10:00 AM',
// 				'High',
// 			],
// 		},
// 		footer: { text: 'This is a notification generated by task.wautopilot.com' },
// 		buttons: [
// 			{
// 				type: 'URL',
// 				text: 'Open Task',
// 				url: 'https://task.wautopilot.com/organizations{{1}}',
// 				example: ['task-id-1'],
// 			},
// 		],
// 	},
// 	{
// 		_id: '499259179221320',
// 		name: 'task_wautopilot_reminder',
// 		status: 'APPROVED',
// 		category: 'UTILITY',
// 		body: {
// 			text: 'Dear {{1}},\n\nThis is a friendly reminder about your upcoming task on Wautopilot. Please review the details below and ensure you complete it on time.\n\n*Remarks* - {{2}}\n\nHere are the task details:\n*Category* - {{3}}\n*Task* - {{4}}\n*Due Date* - {{5}}\n*Priority* - {{6}}',
// 			example: ['Prashant', 'Completed', 'Update_ALL', 'Status Updates', '02nd Aug', 'High'],
// 		},
// 		footer: { text: 'This is a notification generated by task.wautopilot.com' },
// 		buttons: [
// 			{
// 				type: 'URL',
// 				text: 'Open Task',
// 				url: 'https://task.wautopilot.com/organizations{{1}}',
// 				example: ['task-id-1'],
// 			},
// 		],
// 	},
// 	{
// 		_id: '703008418565758',
// 		name: 'bni_first_message',
// 		status: 'APPROVED',
// 		category: 'MARKETING',
// 		body: {
// 			text: '*Good Morning BNI {{1}} Ji,*\n\nThis is Prashant Varma from BNI Athena, Delhi South.\n\nSaw your profile on BNIConnect sometime back.\n\nWhat would be the best way to communicate if I find some relevant referral for you. \n👇👇👇👇👇',
// 			example: ['Name'],
// 		},
// 		buttons: [
// 			{ type: 'QUICK_REPLY', text: 'Whatsappp' },
// 			{ type: 'QUICK_REPLY', text: 'Calll' },
// 			{ type: 'QUICK_REPLY', text: 'SMS' },
// 		],
// 	},
// 	{
// 		_id: '3837455136535795',
// 		name: 'product_catalog',
// 		status: 'APPROVED',
// 		category: 'MARKETING',
// 		body: {
// 			text: "Explore our carefully curated selection of high-quality products below. Each item comes with detailed descriptions, real-time stock availability, and competitive pricing to help you make an informed decision. Don't miss out on these great deals!",
// 			example: [],
// 		},
// 		carousel: [
// 			{
// 				header: {
// 					format: 'IMAGE',
// 					example:
// 						'https://scontent.whatsapp.net/v/t61.29466-34/446073988_1210008903538570_2804296722040795242_n.jpg?ccb=1-7&_nc_sid=a80384&_nc_ohc=L7PyBSxLUGsQ7kNvgEZmLa8&_nc_ht=scontent.whatsapp.net&edm=AH51TzQEAAAA&_nc_gid=Ap_HJ4-ou77rQ0kTCTZWY44&oh=01_Q5AaIIa97iBhiKA5c2_9-toquTwtwvYOJVjB4GKrk_QFIM5l&oe=67318FE6',
// 				},
// 				body: {
// 					text: 'Wireless Noise-Cancelling Headphones, Experience rich sound and block out noise. {{1}} units available costs only ₹{{2}}',
// 					example: ['72', '2000'],
// 				},
// 				buttons: [{ type: 'QUICK_REPLY', text: 'Add to cart' }],
// 			},
// 			{
// 				header: {
// 					format: 'IMAGE',
// 					example:
// 						'https://scontent.whatsapp.net/v/t61.29466-34/421860779_424150463688037_3597448108766093855_n.jpg?ccb=1-7&_nc_sid=a80384&_nc_ohc=NQHtEpXrXMgQ7kNvgGUT9l3&_nc_ht=scontent.whatsapp.net&edm=AH51TzQEAAAA&_nc_gid=Ap_HJ4-ou77rQ0kTCTZWY44&oh=01_Q5AaIPjArIFEt3fCQMQi5HKN0yzlex4F8Err193biNQpAKFZ&oe=67318AEF',
// 				},
// 				body: {
// 					text: 'Smart LED Desk Lamp. Stylish, adjustable brightness lamp perfect for any workspace. {{1}} units available, costs only ₹{{2}}',
// 					example: ['48', '1899'],
// 				},
// 				buttons: [{ type: 'QUICK_REPLY', text: 'Add to cart' }],
// 			},
// 		],
// 	},
// 	{
// 		_id: '513710704705824',
// 		name: 'carousel_with_template_test',
// 		status: 'REJECTED',
// 		category: 'MARKETING',
// 		body: {
// 			text: 'Hello {{1}},\nWe have the following options available with us.',
// 			example: ['Prashant'],
// 		},
// 		carousel: [
// 			{
// 				header: {
// 					format: 'IMAGE',
// 					example:
// 						'https://scontent.whatsapp.net/v/t61.29466-34/324787553_400342233116192_1465130658499341589_n.jpg?ccb=1-7&_nc_sid=a80384&_nc_ohc=HY6K29LIAp0Q7kNvgHUC9KU&_nc_ht=scontent.whatsapp.net&edm=AH51TzQEAAAA&_nc_gid=Ap_HJ4-ou77rQ0kTCTZWY44&oh=01_Q5AaIO-1fq0Caf6w-y8wntPfPzRodp7cNz13rmy4tKGgkLhO&oe=67318FA3',
// 				},
// 				body: {
// 					text: 'This is product 1: {{1}}\nprice: {{2}}\nstock: {{3}}',
// 					example: ['Golden earring', '1200', '10'],
// 				},
// 				buttons: [{ type: 'QUICK_REPLY', text: 'Order' }],
// 			},
// 			{
// 				header: {
// 					format: 'IMAGE',
// 					example:
// 						'https://scontent.whatsapp.net/v/t61.29466-34/461551605_1915328278986597_2475890395404126401_n.jpg?ccb=1-7&_nc_sid=a80384&_nc_ohc=zaV1y9-96ecQ7kNvgEUQoo6&_nc_ht=scontent.whatsapp.net&edm=AH51TzQEAAAA&_nc_gid=Ap_HJ4-ou77rQ0kTCTZWY44&oh=01_Q5AaIGaOpj2NwXbAkNOzJqSe0sdnhzcfnhqUzBiNl1PBcgnV&oe=673188E2',
// 				},
// 				body: {
// 					text: 'This is product 1: {{1}}\nprice: {{2}}\nstock: {{3}}',
// 					example: ['Golden bracelet', '3000', '5'],
// 				},
// 				buttons: [{ type: 'QUICK_REPLY', text: 'Order' }],
// 			},
// 		],
// 	},
// 	{
// 		_id: '526083146723033',
// 		name: 'carousel_with_variables',
// 		status: 'REJECTED',
// 		category: 'MARKETING',
// 		body: { text: 'this is a sample body with variables in cards', example: [] },
// 		carousel: [
// 			{
// 				header: {
// 					format: 'IMAGE',
// 					example:
// 						'https://scontent.whatsapp.net/v/t61.29466-34/399451586_3680279535557579_4114434768510071561_n.jpg?ccb=1-7&_nc_sid=a80384&_nc_ohc=t6rccGXzNs0Q7kNvgH5NhUd&_nc_ht=scontent.whatsapp.net&edm=AH51TzQEAAAA&_nc_gid=Ap_HJ4-ou77rQ0kTCTZWY44&oh=01_Q5AaIGjYgcbILBzwgjPx6-xAmJ4Or53NSSPle_xhkSJE3oA-&oe=67316CBA',
// 				},
// 				body: { text: 'hello {{1}},\nwe got {{2}} number', example: ['john', '1000'] },
// 				buttons: [{ type: 'QUICK_REPLY', text: 'Confirmed' }],
// 			},
// 			{
// 				header: {
// 					format: 'IMAGE',
// 					example:
// 						'https://scontent.whatsapp.net/v/t61.29466-34/461521466_1278515989822224_2769067475939978712_n.jpg?ccb=1-7&_nc_sid=a80384&_nc_ohc=jwylWCTreH0Q7kNvgGSbWDG&_nc_ht=scontent.whatsapp.net&edm=AH51TzQEAAAA&_nc_gid=Ap_HJ4-ou77rQ0kTCTZWY44&oh=01_Q5AaICeMpB9m0MYBV91Si-Q9OkaZodLzyXTMDIyPKrqdHkMH&oe=673171DC',
// 				},
// 				body: { text: 'hello {{1}},\nitems left {{2}}', example: ['john', '20'] },
// 				buttons: [{ type: 'QUICK_REPLY', text: 'Order now' }],
// 			},
// 		],
// 	},
// 	{
// 		_id: '507357192088448',
// 		name: 'sample_carousel_template',
// 		status: 'APPROVED',
// 		category: 'MARKETING',
// 		body: { text: 'sample template body', example: [] },
// 		carousel: [
// 			{
// 				header: {
// 					format: 'IMAGE',
// 					example:
// 						'https://scontent.whatsapp.net/v/t61.29466-34/421888823_567511462613872_7437168376234840126_n.jpg?ccb=1-7&_nc_sid=a80384&_nc_ohc=nuPzeZE7H0wQ7kNvgH9TBek&_nc_ht=scontent.whatsapp.net&edm=AH51TzQEAAAA&_nc_gid=Ap_HJ4-ou77rQ0kTCTZWY44&oh=01_Q5AaIB2ZU_r9MXD_S5AyjPVql91rB7EZfZTg4-swghNPJgJQ&oe=67318DD4',
// 				},
// 				body: { text: 'sample body 1', example: [] },
// 				buttons: [{ type: 'QUICK_REPLY', text: 'test' }],
// 			},
// 			{
// 				header: {
// 					format: 'IMAGE',
// 					example:
// 						'https://scontent.whatsapp.net/v/t61.29466-34/459394144_407668352169001_4302087050457900771_n.jpg?ccb=1-7&_nc_sid=a80384&_nc_ohc=RykMR8RYx1gQ7kNvgGoDmLw&_nc_ht=scontent.whatsapp.net&edm=AH51TzQEAAAA&_nc_gid=Ap_HJ4-ou77rQ0kTCTZWY44&oh=01_Q5AaIBKhhgfGFwABd6DDW_RNqmPFf5_KuC4EzF6YXSQKf9iz&oe=67317D53',
// 				},
// 				body: { text: 'sample body 2', example: [] },
// 				buttons: [{ type: 'QUICK_REPLY', text: 'test 2' }],
// 			},
// 			{
// 				header: {
// 					format: 'IMAGE',
// 					example:
// 						'https://scontent.whatsapp.net/v/t61.29466-34/417678085_1907693496404171_4670733992245415781_n.jpg?ccb=1-7&_nc_sid=a80384&_nc_ohc=FeUQSd4L6qUQ7kNvgHsUs5C&_nc_ht=scontent.whatsapp.net&edm=AH51TzQEAAAA&_nc_gid=Ap_HJ4-ou77rQ0kTCTZWY44&oh=01_Q5AaIK0QhPZF0KhAmDD5MfDquuxKxn53BeC3LEoXPUxjXMG7&oe=67316C60',
// 				},
// 				body: { text: 'sample body 3', example: [] },
// 				buttons: [{ type: 'QUICK_REPLY', text: 'test 3' }],
// 			},
// 		],
// 	},
// 	{
// 		_id: '853831216850857',
// 		name: 'pv_linkedin_facebook_links_message',
// 		status: 'APPROVED',
// 		category: 'MARKETING',
// 		header: {
// 			format: 'IMAGE',
// 			example:
// 				'https://scontent.whatsapp.net/v/t61.29466-34/459095902_853831223517523_6617838058198772727_n.png?ccb=1-7&_nc_sid=8b1bef&_nc_ohc=eU8yZDeoS4gQ7kNvgHoZrCO&_nc_ht=scontent.whatsapp.net&edm=AH51TzQEAAAA&_nc_gid=Ap_HJ4-ou77rQ0kTCTZWY44&oh=01_Q5AaIP2aSZn3F-rhdyx8ZYbtCmAirDYloj9tpmnlHteR_A-t&oe=67319198',
// 		},
// 		body: {
// 			text: 'Lets connect on Social Media also.\n\nPlease click on the button below to connect.\n\n👇👇👇👇',
// 			example: [],
// 		},
// 		buttons: [
// 			{ type: 'URL', text: 'Linkedin', url: 'https://www.linkedin.com/in/coachprashantvarma/' },
// 			{ type: 'URL', text: 'Facebook', url: 'https://www.facebook.com/prashaant.varma' },
// 		],
// 	},
// 	{
// 		_id: '560793779628355',
// 		name: 'sapin40549',
// 		status: 'REJECTED',
// 		category: 'MARKETING',
// 		body: { text: 'qwertyui {{1}}', example: ['asda'] },
// 		carousel: [
// 			{
// 				header: {
// 					format: 'IMAGE',
// 					example:
// 						'https://scontent.whatsapp.net/v/t61.29466-34/442076712_1572018203737367_1757209097769204219_n.jpg?ccb=1-7&_nc_sid=a80384&_nc_ohc=TMkZD4pmDX8Q7kNvgHEKjPm&_nc_ht=scontent.whatsapp.net&edm=AH51TzQEAAAA&_nc_gid=Ap_HJ4-ou77rQ0kTCTZWY44&oh=01_Q5AaILUATLxXzbJfq-wUYgHbb5P5YIfEMsF5EPvTEgGMA2Cx&oe=67317B74',
// 				},
// 				body: { text: 'qwrtyuiop {{1}}', example: ['sdasd'] },
// 				buttons: [
// 					{ type: 'QUICK_REPLY', text: 'Hello' },
// 					{ type: 'QUICK_REPLY', text: 'Hello 2' },
// 				],
// 			},
// 			{
// 				header: {
// 					format: 'IMAGE',
// 					example:
// 						'https://scontent.whatsapp.net/v/t61.29466-34/456049695_868225658746647_2348372313416957380_n.jpg?ccb=1-7&_nc_sid=a80384&_nc_ohc=ARRY-vSIl_UQ7kNvgH6ngV7&_nc_ht=scontent.whatsapp.net&edm=AH51TzQEAAAA&_nc_gid=Ap_HJ4-ou77rQ0kTCTZWY44&oh=01_Q5AaINNUERxZ0F6USrlOKBZBK4hF-WSdBEkDHgNX4GfwYo3B&oe=67319485',
// 				},
// 				body: { text: 'asdfghjkl {{1}}', example: ['v fgs'] },
// 				buttons: [
// 					{ type: 'QUICK_REPLY', text: 'Hello 3' },
// 					{ type: 'QUICK_REPLY', text: 'Hello 4' },
// 				],
// 			},
// 		],
// 	},
// 	{
// 		_id: '1523000151653254',
// 		name: '234',
// 		status: 'APPROVED',
// 		category: 'MARKETING',
// 		body: { text: '234', example: [] },
// 	},
// 	{
// 		_id: '1547477319537802',
// 		name: 'referral_partner_survey',
// 		status: 'APPROVED',
// 		category: 'MARKETING',
// 		body: {
// 			text: 'Good Morning BNI {{1}} {{2}} {{3}},\n\nThis is Prashant Varma from BNI Athena, Delhi South.\n\nSaw your profile some time back on BNI Connect.\n\nI recieved an enquiry for Digital Marketing Services in {{4}}\n\nDo you do Digital Marketing.  \n\nKindly confirm 👇',
// 			example: ['First Name', 'Middle Name', 'Last Name', 'City Name'],
// 		},
// 		buttons: [{ type: 'QUICK_REPLY', text: 'I Do Digital Marketing' }],
// 	},
// 	{
// 		_id: '1030943261773894',
// 		name: 'utility_test_message',
// 		status: 'APPROVED',
// 		category: 'UTILITY',
// 		body: { text: 'You received a new notification, {{1}}', example: ['Name'] },
// 		buttons: [
// 			{ type: 'QUICK_REPLY', text: 'Yes' },
// 			{ type: 'QUICK_REPLY', text: 'No' },
// 		],
// 	},
// 	{
// 		_id: '1747181659355758',
// 		name: 'prashant_real_estate_consultant',
// 		status: 'APPROVED',
// 		category: 'MARKETING',
// 		header: { format: 'TEXT', example: [] },
// 		body: {
// 			text: 'Are you a {{1}} {{2}} Based Real Estate Consultant ?',
// 			example: ['South', 'Delhi'],
// 		},
// 		buttons: [
// 			{ type: 'QUICK_REPLY', text: 'Yes I am in South Delhi' },
// 			{ type: 'QUICK_REPLY', text: 'No I am Not in South Delh' },
// 		],
// 	},
// 	{
// 		_id: '3369298416697493',
// 		name: 'propmatch_plot_requirement',
// 		status: 'APPROVED',
// 		category: 'MARKETING',
// 		body: {
// 			text: 'Hi ,\n\nLooking for a plot or kothi in the following colony for a client.\n\nColony - {{1}} \nSize - {{2}}\n\nKindly confirm if you have something similar available',
// 			example: ['Hauz Khas / Green Park / Safdarjung Enclave', '200 - 300 Sqyd'],
// 		},
// 		footer: { text: 'www.propmatch.in' },
// 		buttons: [
// 			{ type: 'QUICK_REPLY', text: 'Plot Available 00001' },
// 			{ type: 'QUICK_REPLY', text: 'Not Available' },
// 		],
// 	},
// 	{
// 		_id: '823852523056553',
// 		name: 'task_wautopilot_today_overview',
// 		status: 'APPROVED',
// 		category: 'UTILITY',
// 		body: {
// 			text: 'Dear {{1}},\n\n{{2}} has updated the status of the task to *{{3}}*.\n\n*Remarks* - {{4}}\n\nHere are the task details:\n*Category* - {{5}}\n*Task* - {{6}}\n*Due Date* - {{7}}\n*Priority* - {{8}}',
// 			example: [
// 				'Prashant',
// 				'Prashant',
// 				'In Progress',
// 				'Working on this task',
// 				'Accounts',
// 				'Task 1',
// 				'05-Jul-24 10:00 AM',
// 				'High',
// 			],
// 		},
// 		footer: { text: 'This is a notification generated by task.wautopilot.com' },
// 		buttons: [
// 			{
// 				type: 'URL',
// 				text: 'Open Task',
// 				url: 'https://task.wautopilot.com/organizations{{1}}',
// 				example: ['task-id-1'],
// 			},
// 		],
// 	},
// 	{
// 		_id: '950356093128522',
// 		name: 'lead_notification',
// 		status: 'APPROVED',
// 		category: 'MARKETING',
// 		header: { format: 'TEXT', example: [] },
// 		body: {
// 			text: 'Hi {{1}},\n\nThe following person has downloaded your contact card.\n\n*Name*: {{2}}\n*Contact Number*: {{3}}\n*Message Received*:  {{4}}\n\nRegards,\nSaveMyVCard',
// 			example: ['Prashant', 'Manzar', '919718793635', 'Contact Card for Prashant Varma'],
// 		},
// 		buttons: [{ type: 'QUICK_REPLY', text: 'Get Contact Card' }],
// 	},
// 	{
// 		_id: '7846637745396362',
// 		name: 'send_callback_button',
// 		status: 'APPROVED',
// 		category: 'MARKETING',
// 		header: { format: 'TEXT', example: [] },
// 		body: { text: 'Hi,\n\nThis is just to check the callback button on whatsapp.', example: [] },
// 		buttons: [{ type: 'VOICE_CALL', text: 'Get in touch' }],
// 	},
// 	{
// 		_id: '377289165329696',
// 		name: 'whatsapp_calling_butoon_testing',
// 		status: 'APPROVED',
// 		category: 'MARKETING',
// 		body: { text: 'whatsapp call testing from button', example: [] },
// 		buttons: [{ type: 'VOICE_CALL', text: 'Whatsapp Call' }],
// 	},
// 	{
// 		_id: '750640087231581',
// 		name: 'bni_requirement',
// 		status: 'APPROVED',
// 		category: 'MARKETING',
// 		body: {
// 			text: 'Hi {{1}} ,\n\n{{2}}.\n\nKindly let me know if you deal in it or know another BNI member. \n\nRegards,\nPrashant Varma',
// 			example: ['Name', 'Specific Ask'],
// 		},
// 		buttons: [
// 			{ type: 'QUICK_REPLY', text: 'I deal in this' },
// 			{ type: 'QUICK_REPLY', text: "I don't deal in this" },
// 		],
// 	},
// 	{
// 		_id: '780197390878909',
// 		name: 'bni_bniconnect_connection_request',
// 		status: 'APPROVED',
// 		category: 'MARKETING',
// 		body: {
// 			text: '*Good Morning BNI* {{1}} ,\n\nSent you request on your BNIConnect Profile few days back , please accept it . \n\nAlso wanted to know the best way to stay connected with you .\n\nRegards,\nName - Prashant Varma\nCategory - Performance Coach\nUSP - Helping Businesses grow with the power of Whatsapp\nChapter - BNI Athena\nRegion - Delhi South',
// 			example: ['Name'],
// 		},
// 		buttons: [
// 			{ type: 'QUICK_REPLY', text: 'Whatsapp' },
// 			{ type: 'QUICK_REPLY', text: 'Connect on Linkedin' },
// 			{ type: 'QUICK_REPLY', text: 'I have left BNI' },
// 		],
// 	},
// 	{
// 		_id: '1144349926608624',
// 		name: 'bni_group_joining_message1',
// 		status: 'APPROVED',
// 		category: 'MARKETING',
// 		body: {
// 			text: 'Hi {{1}} ,\n\nBased on your request here is the group link based on your business address listed.\n\n{{2}}\n\nIf the above address is correct.\n\nPlease join Nearby Business Network Group  {{3}}',
// 			example: ['Name', 'address', 'link'],
// 		},
// 	},
// 	{
// 		_id: '724318373199783',
// 		name: 'mar_bni_pincode_message',
// 		status: 'APPROVED',
// 		category: 'MARKETING',
// 		body: {
// 			text: 'Good Morning BNI {{1}} ,\n\nWhile going through BNIConnect a few days ago, I saw your office is in {{2}} .\n\nI visit {{2}} regularly, and would like to do 1-2-1 when I visit next time .\n\nPlease share your *Google Location of your Business* .\n\nRegards,\nPrashant Varma\nPerformance Coach\nBNI Athena, Delhi South',
// 			example: ['Name', 'Colony'],
// 		},
// 		buttons: [
// 			{ type: 'QUICK_REPLY', text: "Let's Connect" },
// 			{ type: 'QUICK_REPLY', text: 'I will connect later' },
// 		],
// 	},
// 	{
// 		_id: '7228429823920445',
// 		name: 'thank_you_bni_message_vcard',
// 		status: 'APPROVED',
// 		category: 'MARKETING',
// 		body: {
// 			text: 'Thank you for your response.\n\n*Please save my contact Card* for future reference.',
// 			example: [],
// 		},
// 	},
// ];

export default async function Layout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const templates = (await TemplateService.listTemplates())!;

	return (
		<Suspense fallback={<Loading />}>
			<section>
				<TemplatesProvider data={templates!}>{children}</TemplatesProvider>
			</section>
		</Suspense>
	);
}
