import { ChatbotProvider } from '@/components/context/chatbots';
import { TemplatesProvider } from '@/components/context/templates';
import Loading from '@/components/elements/loading';
import { TemplateWithID } from '@/schema/template';
import ChatBotService from '@/services/chatbot.service';
import { Metadata } from 'next';
import { Suspense } from 'react';

export const metadata: Metadata = {
	title: 'Campaigns • Wautopilot',
};

export default async function Layout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const chatbotList = (await ChatBotService.listChatBots())!;
	// const templateList = (await TemplateService.listTemplates())!;

	const templateList = [
		{
			id: '499259179221320',
			name: 'task_wautopilot_reminder',
			status: 'APPROVED',
			category: 'UTILITY',
			components: [
				{
					type: 'BODY',
					text: 'Dear {{1}},\n\nThis is a friendly reminder about your upcoming task on Wautopilot. Please review the details below and ensure you complete it on time.\n\n*Remarks* - {{2}}\n\nHere are the task details:\n*Category* - {{3}}\n*Task* - {{4}}\n*Due Date* - {{5}}\n*Priority* - {{6}}',
					example: {
						body_text: [
							['Prashant', 'Completed', 'Update_ALL', 'Status Updates', '02nd Aug', 'High'],
						],
					},
				},
				{
					type: 'FOOTER',
					text: 'This is a notification generated by task.wautopilot.com',
				},
				{
					type: 'BUTTONS',
					buttons: [
						{
							type: 'URL',
							text: 'Open Task',
							url: 'https://task.wautopilot.com/organizations{{1}}',
							example: ['task-id-1'],
						},
					],
				},
			],
		},
		{
			id: '406861508512098',
			name: 'task_wautopilot_status_update',
			status: 'APPROVED',
			category: 'UTILITY',
			components: [
				{
					type: 'BODY',
					text: 'Dear {{1}},\n\n{{2}} has updated the status of the task to *{{3}}*.\n\n*Remarks* - {{4}}\n\nHere are the task details:\n*Category* - {{5}}\n*Task* - {{6}}\n*Due Date* - {{7}}\n*Priority* - {{8}}',
					example: {
						body_text: [
							[
								'Prashant',
								'Prashant',
								'In Progress',
								'Working on this task',
								'Accounts',
								'Task 1',
								'05-Jul-24 10:00 AM',
								'High',
							],
						],
					},
				},
				{
					type: 'FOOTER',
					text: 'This is a notification generated by task.wautopilot.com',
				},
				{
					type: 'BUTTONS',
					buttons: [
						{
							type: 'URL',
							text: 'Open Task',
							url: 'https://task.wautopilot.com/organizations{{1}}',
							example: ['task-id-1'],
						},
					],
				},
			],
		},
		{
			id: '823852523056553',
			name: 'task_wautopilot_today_overview',
			status: 'APPROVED',
			category: 'UTILITY',
			components: [
				{
					type: 'BODY',
					text: 'Dear {{1}},\n\n{{2}} has updated the status of the task to *{{3}}*.\n\n*Remarks* - {{4}}\n\nHere are the task details:\n*Category* - {{5}}\n*Task* - {{6}}\n*Due Date* - {{7}}\n*Priority* - {{8}}',
					example: {
						body_text: [
							[
								'Prashant',
								'Prashant',
								'In Progress',
								'Working on this task',
								'Accounts',
								'Task 1',
								'05-Jul-24 10:00 AM',
								'High',
							],
						],
					},
				},
				{
					type: 'FOOTER',
					text: 'This is a notification generated by task.wautopilot.com',
				},
				{
					type: 'BUTTONS',
					buttons: [
						{
							type: 'URL',
							text: 'Open Task',
							url: 'https://task.wautopilot.com/organizations{{1}}',
							example: ['task-id-1'],
						},
					],
				},
			],
		},
		{
			id: '8000423059997120',
			name: 'task_wautopilot_status_create',
			status: 'APPROVED',
			category: 'UTILITY',
			components: [
				{
					type: 'BODY',
					text: 'Dear {{1}},\n\n{{2}} has assigned a task with status *{{3}}*.\n\n*Remarks* - {{4}}\n\nHere are the task details:\n*Category* - {{5}}\n*Task* - {{6}}\n*Due Date* - {{7}}\n*Priority* - {{8}}',
					example: {
						body_text: [
							[
								'Prashant',
								'Prashant',
								'In Progress',
								'Working on this task',
								'Accounts',
								'Task 1',
								'05-Jul-24 10:00 AM',
								'High',
							],
						],
					},
				},
				{
					type: 'FOOTER',
					text: 'This is a notification generated by task.wautopilot.com',
				},
				{
					type: 'BUTTONS',
					buttons: [
						{
							type: 'URL',
							text: 'Open Task',
							url: 'https://task.wautopilot.com/organizations{{1}}',
							example: ['task-id-1'],
						},
					],
				},
			],
		},
		{
			id: '1443758116304073',
			name: 'bni_first_message_with_contact_card',
			status: 'APPROVED',
			category: 'MARKETING',
			components: [
				{
					type: 'BODY',
					text: 'Dear {{1}}, \n\nI saw your profile on BNIConnect few days back would like to add you to my List of preferred partners to pass on relevant referrals in your City.\n\nKindly let me know the best way to keep in touch \n{{2}}',
					example: {
						body_text: [['Prashant', '8989898989']],
					},
				},
				{
					type: 'FOOTER',
					text: 'www.savemyvcard.com',
				},
				{
					type: 'BUTTONS',
					buttons: [
						{
							type: 'QUICK_REPLY',
							text: 'Whatsapp',
						},
					],
				},
			],
		},
		{
			id: '703008418565758',
			name: 'bni_first_message',
			status: 'APPROVED',
			category: 'MARKETING',
			components: [
				{
					type: 'HEADER',
					format: 'IMAGE',
					example: {
						header_handle: [
							'https://scontent.whatsapp.net/v/t61.29466-34/402317428_703008421899091_3202757223797594522_n.jpg?ccb=1-7&_nc_sid=8b1bef&_nc_ohc=YQzmohUiVX4Q7kNvgFoaX34&_nc_ht=scontent.whatsapp.net&edm=AH51TzQEAAAA&oh=01_Q5AaIDYsRoHCLDf8eAVu6K5xaUw78_dvghCj18UVpp-y7jYi&oe=66E06291',
						],
					},
				},
				{
					type: 'BODY',
					text: 'Dear {{1}}, \n\nI saw your profile on BNI and found an interesting fact that there are {{2}} members nearby your business.\n\nTo connect with these members kindly click on *I want to join*',
					example: {
						body_text: [['Prashant', '50']],
					},
				},
				{
					type: 'BUTTONS',
					buttons: [
						{
							type: 'QUICK_REPLY',
							text: 'I want to join',
						},
						{
							type: 'QUICK_REPLY',
							text: 'I am not a member',
						},
					],
				},
			],
		},
		{
			id: '950356093128522',
			name: 'lead_notification',
			status: 'APPROVED',
			category: 'MARKETING',
			components: [
				{
					type: 'HEADER',
					format: 'TEXT',
					text: 'Notification from Save My V Card',
				},
				{
					type: 'BODY',
					text: 'Hi {{1}},\n\nThe following person has downloaded your contact card.\n\n*Name*: {{2}}\n*Contact Number*: {{3}}\n*Message Received*:  {{4}}\n\nRegards,\nSaveMyVCard',
					example: {
						body_text: [['Prashant', 'Manzar', '919718793635', 'Contact Card for Prashant Varma']],
					},
				},
				{
					type: 'BUTTONS',
					buttons: [
						{
							type: 'QUICK_REPLY',
							text: 'Get Contact Card',
						},
					],
				},
			],
		},
		{
			id: '7846637745396362',
			name: 'send_callback_button',
			status: 'APPROVED',
			category: 'MARKETING',
			components: [
				{
					type: 'HEADER',
					format: 'TEXT',
					text: 'CALL BACK BUTTON TESTING',
				},
				{
					type: 'BODY',
					text: 'Hi,\n\nThis is just to check the callback button on whatsapp.',
				},
				{
					type: 'BUTTONS',
					buttons: [
						{
							type: 'VOICE_CALL',
							text: 'Get in touch',
						},
					],
				},
			],
		},
		{
			id: '377289165329696',
			name: 'whatsapp_calling_butoon_testing',
			status: 'APPROVED',
			category: 'MARKETING',
			components: [
				{
					type: 'BODY',
					text: 'whatsapp call testing from button',
				},
				{
					type: 'BUTTONS',
					buttons: [
						{
							type: 'VOICE_CALL',
							text: 'Whatsapp Call',
						},
					],
				},
			],
		},
		{
			id: '343662955094467',
			name: 'bni_inc_mumbai_2024_1',
			status: 'APPROVED',
			category: 'MARKETING',
			components: [
				{
					type: 'BODY',
					text: 'Hi {{1}} ,  \n\nWill you be attending *BNI India National Conference 22nd & 23rd June 2024 Mumbai.*  \n\nKindly choose the below option or share with your Chapter members.',
					example: {
						body_text: [['Name']],
					},
				},
				{
					type: 'BUTTONS',
					buttons: [
						{
							type: 'URL',
							text: 'Will attend BNI Mumbai Ev',
							url: 'https://open.whatsleads.in/XrW10X',
						},
					],
				},
			],
		},
		{
			id: '1177370706951757',
			name: 'bni_inc_mumbai_2024',
			status: 'APPROVED',
			category: 'MARKETING',
			components: [
				{
					type: 'BODY',
					text: 'Hi {{1}} ,  \n\nWill you be attending *BNI India National Conference 22nd & 23rd June 2024 Mumbai.*  \n\nKindly choose the below option or share with your Chapter members.',
					example: {
						body_text: [['Name']],
					},
				},
				{
					type: 'BUTTONS',
					buttons: [
						{
							type: 'URL',
							text: 'Will attend BNI Mumbai Ev',
							url: 'https://open.whatsleads.in/XrW10X{{1}}',
							example: ['https://open.whatsleads.in/XrW10X'],
						},
					],
				},
			],
		},
		{
			id: '750640087231581',
			name: 'bni_requirement',
			status: 'APPROVED',
			category: 'MARKETING',
			components: [
				{
					type: 'BODY',
					text: 'Hi {{1}} ,\n\n{{2}}.\n\nKindly let me know if you deal in it or know another BNI member. \n\nRegards,\nPrashant Varma',
					example: {
						body_text: [['Name', 'Specific Ask']],
					},
				},
				{
					type: 'BUTTONS',
					buttons: [
						{
							type: 'QUICK_REPLY',
							text: 'I deal in this',
						},
						{
							type: 'QUICK_REPLY',
							text: "I don't deal in this",
						},
					],
				},
			],
		},
		{
			id: '780197390878909',
			name: 'bni_bniconnect_connection_request',
			status: 'APPROVED',
			category: 'MARKETING',
			components: [
				{
					type: 'BODY',
					text: '*Good Morning BNI* {{1}} ,\n\nSent you request on your BNIConnect Profile few days back , please accept it . \n\nAlso wanted to know the best way to stay connected with you .\n\nRegards,\nName - Prashant Varma\nCategory - Performance Coach\nUSP - Helping Businesses grow with the power of Whatsapp\nChapter - BNI Athena\nRegion - Delhi South',
					example: {
						body_text: [['Name']],
					},
				},
				{
					type: 'BUTTONS',
					buttons: [
						{
							type: 'QUICK_REPLY',
							text: 'Whatsapp',
						},
						{
							type: 'QUICK_REPLY',
							text: 'Connect on Linkedin',
						},
						{
							type: 'QUICK_REPLY',
							text: 'I have left BNI',
						},
					],
				},
			],
		},
		{
			id: '1144349926608624',
			name: 'bni_group_joining_message1',
			status: 'APPROVED',
			category: 'MARKETING',
			components: [
				{
					type: 'BODY',
					text: 'Hi {{1}} ,\n\nBased on your request here is the group link based on your business address listed.\n\n{{2}}\n\nIf the above address is correct.\n\nPlease join Nearby Business Network Group  {{3}}',
					example: {
						body_text: [['Name', 'address', 'link']],
					},
				},
			],
		},
		{
			id: '724318373199783',
			name: 'mar_bni_pincode_message',
			status: 'APPROVED',
			category: 'MARKETING',
			components: [
				{
					type: 'BODY',
					text: 'Good Morning BNI {{1}} ,\n\nWhile going through BNIConnect a few days ago, I saw your office is in {{2}} .\n\nI visit {{2}} regularly, and would like to do 1-2-1 when I visit next time .\n\nPlease share your *Google Location of your Business* .\n\nRegards,\nPrashant Varma\nPerformance Coach\nBNI Athena, Delhi South',
					example: {
						body_text: [['Name', 'Colony']],
					},
				},
				{
					type: 'BUTTONS',
					buttons: [
						{
							type: 'QUICK_REPLY',
							text: "Let's Connect",
						},
						{
							type: 'QUICK_REPLY',
							text: 'I will connect later',
						},
					],
				},
			],
		},
		{
			id: '7228429823920445',
			name: 'thank_you_bni_message_vcard',
			status: 'APPROVED',
			category: 'MARKETING',
			components: [
				{
					type: 'BODY',
					text: 'Thank you for your response.\n\n*Please save my contact Card* for future reference.',
				},
			],
		},
		{
			id: '943212587422720',
			name: 'mar_bni_community1',
			status: 'APPROVED',
			category: 'MARKETING',
			components: [
				{
					type: 'BODY',
					text: 'https://chat.whatsapp.com/DOcFgvTpAyHGuTKOAmvXlg',
				},
				{
					type: 'BUTTONS',
					buttons: [
						{
							type: 'URL',
							text: 'Delhi Nearby Business',
							url: 'https://bit.ly/BNI_Whatsapp_Community_Delhi',
						},
					],
				},
			],
		},
		{
			id: '3174156109386348',
			name: 'mar_after_exhibiion_message',
			status: 'APPROVED',
			category: 'MARKETING',
			components: [
				{
					type: 'BODY',
					text: 'Hello {{1}} ,\n\nDid you attend {{2}} ?\n\nRegards,\nPrashant Varma',
					example: {
						body_text: [['Name', 'Exhibition']],
					},
				},
				{
					type: 'FOOTER',
					text: 'Powered by : wa.savemyvcard.com',
				},
			],
		},
		{
			id: '965895858578875',
			name: 'mar_exhibition_lead_generation',
			status: 'APPROVED',
			category: 'MARKETING',
			components: [
				{
					type: 'BODY',
					text: 'Hi  {{1}},\n\nAre you attending {{2}} ?\n\nKindly share your Stall / booth details and if possible google location.\n\nWill meet you if I get the opportunity.\n\nRegards,\nPrashant Varma',
					example: {
						body_text: [['Name', 'Exhibition']],
					},
				},
				{
					type: 'FOOTER',
					text: 'www.SaveMyVCard.com',
				},
			],
		},
		{
			id: '731482685631167',
			name: 'naukri_first_message',
			status: 'APPROVED',
			category: 'MARKETING',
			components: [
				{
					type: 'BODY',
					text: 'Hi *{{1}}*,\n\nWe got your details from *{{2}}*.\n\nWe found some jobs nearby your residence for *{{3}}*.\n\nIf Interested, kindly click on *Yes Nearby Naukri*\n\nRegards,\n*Team Nearby Naukri*',
					example: {
						body_text: [['Candidate Name', 'Job Portal Name', 'Job Requirement Title']],
					},
				},
				{
					type: 'BUTTONS',
					buttons: [
						{
							type: 'QUICK_REPLY',
							text: 'Yes Nearby Naukri',
						},
						{
							type: 'QUICK_REPLY',
							text: "No , I don't want Job",
						},
					],
				},
			],
		},
		{
			id: '914676950062961',
			name: 'get_your_vcard',
			status: 'APPROVED',
			category: 'MARKETING',
			components: [
				{
					type: 'BODY',
					text: 'Do you want to *Increase your sales* using *Save My V Card* automated V Card sharing on whatsapp ?',
				},
				{
					type: 'BUTTONS',
					buttons: [
						{
							type: 'URL',
							text: 'Yes',
							url: 'https://savemyvcard.in/',
						},
					],
				},
			],
		},
		{
			id: '2237268986468771',
			name: 'exhibition_lead_generation',
			status: 'APPROVED',
			category: 'MARKETING',
			components: [
				{
					type: 'BODY',
					text: 'Hi {{1}},\n\nDo you want to capture 1000s of leads from your upcoming {{2}} using whatsapp & AI ?',
					example: {
						body_text: [['Manzar', 'Noida Exhibition']],
					},
				},
				{
					type: 'BUTTONS',
					buttons: [
						{
							type: 'QUICK_REPLY',
							text: 'Yes I want 1000s of lead',
						},
						{
							type: 'QUICK_REPLY',
							text: 'I am not an exhibitor',
						},
						{
							type: 'QUICK_REPLY',
							text: 'I do not want leads',
						},
					],
				},
			],
		},
		{
			id: '366248076091059',
			name: 'sendcontactcard',
			status: 'APPROVED',
			category: 'UTILITY',
			components: [
				{
					type: 'HEADER',
					format: 'IMAGE',
					example: {
						header_handle: [
							'https://scontent.whatsapp.net/v/t61.29466-34/380019159_385823327466867_6699687956423518306_n.jpg?ccb=1-7&_nc_sid=8b1bef&_nc_ohc=0YRt9iRxaj8Q7kNvgEJKwsJ&_nc_ht=scontent.whatsapp.net&edm=AH51TzQEAAAA&oh=01_Q5AaIAlpcv4PkPOpIau3fGhpg3o7pS0GAYMYjC_0pDRF4_R5&oe=66E06A4A',
						],
					},
				},
				{
					type: 'BODY',
					text: 'Thank you for submitting your details.\n\n*Step 1* - Ask 3 existing BNI members to send your mobile number to *+919654876000* so that your membership can be verified .  \n\n*Step 2* - After step 1 kindly send your business pincode to *+919999389493* to get added in the group',
				},
			],
		},
		{
			id: '358688210206300',
			name: 'bni_welcome',
			status: 'APPROVED',
			category: 'MARKETING',
			components: [
				{
					type: 'BODY',
					text: 'Hi {{1}}, \n\n*Good Morning BNI*. \n\nI have sent you a connection request on BNI Connect.\n\nKindly accept it. \n\nBest Regards, \nPrashant Varma\nBNI Athena\nBNI Delhi South',
					example: {
						body_text: [['Prashant Ji']],
					},
				},
				{
					type: 'BUTTONS',
					buttons: [
						{
							type: 'QUICK_REPLY',
							text: 'I have accepted',
						},
						{
							type: 'QUICK_REPLY',
							text: 'Thank You',
						},
					],
				},
			],
		},
		{
			id: '352336944071563',
			name: 'hello_world',
			status: 'APPROVED',
			category: 'UTILITY',
			components: [
				{
					type: 'HEADER',
					format: 'TEXT',
					text: 'Hello World',
				},
				{
					type: 'BODY',
					text: 'Welcome and congratulations!! This message demonstrates your ability to send a WhatsApp message notification from the Cloud API, hosted by Meta. Thank you for taking the time to test with us.',
				},
				{
					type: 'FOOTER',
					text: 'WhatsApp Business Platform sample message',
				},
			],
		},
	] as TemplateWithID[];

	return (
		<Suspense fallback={<Loading />}>
			<section>
				<TemplatesProvider data={templateList}>
					<ChatbotProvider data={chatbotList}>{children}</ChatbotProvider>
				</TemplatesProvider>
			</section>
		</Suspense>
	);
}
