import { MediaProvider } from '@/components/context/media';
import { TemplatesProvider } from '@/components/context/templates';
import Loading from '@/components/elements/loading';
import MediaService from '@/services/media.service';
import TemplateService from '@/services/template.service';
import { Metadata } from 'next';
import { Suspense } from 'react';

export const metadata: Metadata = {
	title: 'Campaign • Wautopilot',
};

const templates = [
	{
		id: '3837455136535795',
		name: 'product_catalog',
		status: 'APPROVED',
		category: 'MARKETING',
		body: {
			text: "Explore our carefully curated selection of high-quality products below. Each item comes with detailed descriptions, real-time stock availability, and competitive pricing to help you make an informed decision. Don't miss out on these great deals!",
			example: [],
		},
		carousel: {
			cards: [
				{
					header: {
						format: 'IMAGE',
						example:
							'https://scontent.whatsapp.net/v/t61.29466-34/462403375_1199604274670552_6840903388769463309_n.jpg?ccb=1-7&_nc_sid=a80384&_nc_ohc=JALsCjRCnMwQ7kNvgHX0MgP&_nc_ht=scontent.whatsapp.net&edm=AH51TzQEAAAA&_nc_gid=AnaJsX6uZum4NOL3you1z2G&oh=01_Q5AaID1qhrujm1KrwG51IDQXcdHDQQ7La7bnbE4fHFvgvgdx&oe=6736ACF9',
					},
					body: {
						text: 'Wireless Noise-Cancelling Headphones, Experience rich sound and block out noise. {{1}} units available costs only ₹{{2}}',
						example: ['72', '2000'],
					},
					buttons: [{ type: 'QUICK_REPLY', text: 'Add to cart' }],
				},
				{
					header: {
						format: 'IMAGE',
						example:
							'https://scontent.whatsapp.net/v/t61.29466-34/454167513_8517166141701549_5003082482593421988_n.jpg?ccb=1-7&_nc_sid=a80384&_nc_ohc=egnM01daxaQQ7kNvgEoOz-z&_nc_ht=scontent.whatsapp.net&edm=AH51TzQEAAAA&_nc_gid=AnaJsX6uZum4NOL3you1z2G&oh=01_Q5AaIO5ts3BnfBONWNJc7vfYmdIA1_IAB0KS1uF5ZwcSMb5v&oe=6736B558',
					},
					body: {
						text: 'Smart LED Desk Lamp. Stylish, adjustable brightness lamp perfect for any workspace. {{1}} units available, costs only ₹{{2}}',
						example: ['48', '1899'],
					},
					buttons: [{ type: 'QUICK_REPLY', text: 'Add to cart' }],
				},
			],
		},
	},
	{
		id: '1523000151653254',
		name: '234',
		status: 'APPROVED',
		category: 'MARKETING',
		header: { format: 'TEXT', text: 'Hyy {{1}}', example: ['Sir'] },
		body: { text: 'How are you {{1}}', example: ['sir'] },
	},
	{
		id: '8489070834520910',
		name: 'jewellery_catalog',
		status: 'APPROVED',
		category: 'MARKETING',
		body: {
			text: 'Welcome {{1}} to our jewellery store.\nFeel free to choose your favourite from our product catalog',
			example: ['Name'],
		},
	},
	{
		id: '406861508512098',
		name: 'task_wautopilot_status_update',
		status: 'APPROVED',
		category: 'UTILITY',
		body: {
			text: 'Dear {{1}},\n\n{{2}} has updated the status of the task to *{{3}}*.\n\n*Remarks* - {{4}}\n\nHere are the task details:\n*Category* - {{5}}\n*Task* - {{6}}\n*Due Date* - {{7}}\n*Priority* - {{8}}',
			example: [
				'Prashant',
				'Prashant',
				'In Progress',
				'Working on this task',
				'Accounts',
				'Task 1',
				'05-Jul-24 10:00 AM',
				'High',
			],
		},
		footer: { text: 'This is a notification generated by task.wautopilot.com' },
		buttons: [
			{
				type: 'URL',
				text: 'Open Task',
				url: 'https://task.wautopilot.com/organizations{{1}}',
				example: ['task-id-1'],
			},
		],
	},
	{
		id: '8000423059997120',
		name: 'task_wautopilot_status_create',
		status: 'APPROVED',
		category: 'UTILITY',
		body: {
			text: 'Dear {{1}},\n\n{{2}} has assigned a task with status *{{3}}*.\n\n*Remarks* - {{4}}\n\nHere are the task details:\n*Category* - {{5}}\n*Task* - {{6}}\n*Due Date* - {{7}}\n*Priority* - {{8}}',
			example: [
				'Prashant',
				'Prashant',
				'In Progress',
				'Working on this task',
				'Accounts',
				'Task 1',
				'05-Jul-24 10:00 AM',
				'High',
			],
		},
		footer: { text: 'This is a notification generated by task.wautopilot.com' },
		buttons: [
			{
				type: 'URL',
				text: 'Open Task',
				url: 'https://task.wautopilot.com/organizations{{1}}',
				example: ['task-id-1'],
			},
		],
	},
	{
		id: '703008418565758',
		name: 'bni_first_message',
		status: 'APPROVED',
		category: 'MARKETING',
		body: {
			text: '*Good Morning BNI {{1}} Ji,*\n\nThis is Prashant Varma from BNI Athena, Delhi South.\n\nSaw your profile on BNIConnect sometime back.\n\nWhat would be the best way to communicate if I find some relevant referral for you. \n👇👇👇👇👇',
			example: ['Name'],
		},
		buttons: [
			{ type: 'QUICK_REPLY', text: 'Whatsappp' },
			{ type: 'QUICK_REPLY', text: 'Calll' },
			{ type: 'QUICK_REPLY', text: 'SMS' },
		],
	},
	{
		id: '1037848077881368',
		name: 'referral_partner_survey_digital_marketing',
		status: 'APPROVED',
		category: 'MARKETING',
		body: {
			text: 'Good Morning BNI {{1}} Ji,\n\nThis is Prashant Varma from BNI Athena, Delhi South.\n\nGot your reference sometime back from a BNI Group.\n\nI recieved an enquiry for Digital Marketing Services in {{2}}\n\nDo you do Digital Marketing ?\n\nKindly confirm 👇',
			example: ['First Name', 'City'],
		},
		buttons: [{ type: 'QUICK_REPLY', text: 'I Do Digital Marketing' }],
	},
	{
		id: '526083146723033',
		name: 'carousel_with_variables',
		status: 'REJECTED',
		category: 'MARKETING',
		body: { text: 'this is a sample body with variables in cards', example: [] },
		carousel: {
			cards: [
				{
					header: {
						format: 'IMAGE',
						example:
							'https://scontent.whatsapp.net/v/t61.29466-34/461654352_596100626324181_6695337937984875956_n.jpg?ccb=1-7&_nc_sid=a80384&_nc_ohc=E-Oa9xcz2O8Q7kNvgEPLE6E&_nc_ht=scontent.whatsapp.net&edm=AH51TzQEAAAA&_nc_gid=AnaJsX6uZum4NOL3you1z2G&oh=01_Q5AaILNt6uOYjTmoFKzGurAM0sUFTFn_QjzVi3SMHTnOFms9&oe=6736B244',
					},
					body: { text: 'hello {{1}}, we got {{2}} number', example: ['john', '1000'] },
					buttons: [
						{
							type: 'URL',
							text: 'Google',
							url: 'https://google.com/search?q{{1}}',
							example: ['sanskar'],
						},
					],
				},
				{
					header: {
						format: 'IMAGE',
						example:
							'https://scontent.whatsapp.net/v/t61.29466-34/459778900_937817261590132_910652480204964646_n.jpg?ccb=1-7&_nc_sid=a80384&_nc_ohc=IrOfYN7T6yoQ7kNvgG-eS26&_nc_ht=scontent.whatsapp.net&edm=AH51TzQEAAAA&_nc_gid=AnaJsX6uZum4NOL3you1z2G&oh=01_Q5AaIBD4qXqA1bLuG3AFZYYCP2AhOcwYzVpbb21AQJjrIVtz&oe=6736D36E',
					},
					body: { text: 'hello {{1}}, items left {{2}}', example: ['john', '20'] },
					buttons: [
						{
							type: 'URL',
							text: 'Google',
							url: 'https://google.com/search?q{{1}}',
							example: ['sanskar'],
						},
					],
				},
			],
		},
	},
	{
		id: '513710704705824',
		name: 'carousel_with_template_test',
		status: 'REJECTED',
		category: 'MARKETING',
		body: {
			text: 'Hello {{1}},\nWe have the following options available with us.',
			example: ['Prashant'],
		},
		carousel: {
			cards: [
				{
					header: {
						format: 'IMAGE',
						example:
							'https://scontent.whatsapp.net/v/t61.29466-34/462290352_1649184782307924_7912362098686650461_n.jpg?ccb=1-7&_nc_sid=a80384&_nc_ohc=i8Ag-G3TuIwQ7kNvgFg0e9y&_nc_ht=scontent.whatsapp.net&edm=AH51TzQEAAAA&_nc_gid=AnaJsX6uZum4NOL3you1z2G&oh=01_Q5AaIA2QjbQRPvUzzQOyiLdoVlausM6hM8_Zwj5Rs7WnCvAW&oe=6736AEA0',
					},
					body: {
						text: 'This is product 1: {{1}} price: {{2}} stock: {{3}}',
						example: ['Golden earring', '1200', '10'],
					},
					buttons: [{ type: 'QUICK_REPLY', text: 'Order' }],
				},
				{
					header: {
						format: 'IMAGE',
						example:
							'https://scontent.whatsapp.net/v/t61.29466-34/462064862_1661375811095947_730097525161710550_n.jpg?ccb=1-7&_nc_sid=a80384&_nc_ohc=8DOViFD7bjMQ7kNvgG-NZhb&_nc_ht=scontent.whatsapp.net&edm=AH51TzQEAAAA&_nc_gid=AnaJsX6uZum4NOL3you1z2G&oh=01_Q5AaIHNcTGexKYBDiXTP70XHwyZS3fHuHVzHMxt311RuUJSR&oe=6736AC8A',
					},
					body: {
						text: 'This is product 1: {{1}} price: {{2}} stock: {{3}}',
						example: ['Golden bracelet', '3000', '5'],
					},
					buttons: [{ type: 'QUICK_REPLY', text: 'Order' }],
				},
			],
		},
	},
	{
		id: '499259179221320',
		name: 'task_wautopilot_reminder',
		status: 'APPROVED',
		category: 'UTILITY',
		body: {
			text: 'Dear {{1}},\n\nThis is a friendly reminder about your upcoming task on Wautopilot. Please review the details below and ensure you complete it on time.\n\n*Remarks* - {{2}}\n\nHere are the task details:\n*Category* - {{3}}\n*Task* - {{4}}\n*Due Date* - {{5}}\n*Priority* - {{6}}',
			example: ['Prashant', 'Completed', 'Update_ALL', 'Status Updates', '02nd Aug', 'High'],
		},
		footer: { text: 'This is a notification generated by task.wautopilot.com' },
		buttons: [
			{
				type: 'URL',
				text: 'Open Task',
				url: 'https://task.wautopilot.com/organizations{{1}}',
				example: ['task-id-1'],
			},
		],
	},
	{
		id: '507357192088448',
		name: 'sample_carousel_template',
		status: 'APPROVED',
		category: 'MARKETING',
		body: { text: 'sample template body', example: [] },
		carousel: {
			cards: [
				{
					header: {
						format: 'IMAGE',
						example:
							'https://scontent.whatsapp.net/v/t61.29466-34/421888823_567511462613872_7437168376234840126_n.jpg?ccb=1-7&_nc_sid=a80384&_nc_ohc=ZMRoyUbYo4wQ7kNvgEyrfpw&_nc_ht=scontent.whatsapp.net&edm=AH51TzQEAAAA&_nc_gid=AnaJsX6uZum4NOL3you1z2G&oh=01_Q5AaILSLNiyZiGOKjXnhAxvoscg4IM5T-673EKA9HDWS_9Ns&oe=6736D3D4',
					},
					body: { text: 'sample body 1', example: [] },
					buttons: [{ type: 'QUICK_REPLY', text: 'test' }],
				},
				{
					header: {
						format: 'IMAGE',
						example:
							'https://scontent.whatsapp.net/v/t61.29466-34/459394144_407668352169001_4302087050457900771_n.jpg?ccb=1-7&_nc_sid=a80384&_nc_ohc=veFembfD1C4Q7kNvgGPgOr1&_nc_ht=scontent.whatsapp.net&edm=AH51TzQEAAAA&_nc_gid=AnaJsX6uZum4NOL3you1z2G&oh=01_Q5AaIBHfH7b3xo_qDbeexT2YRVS-Kh9bzKtk3nQR8UUMxmTH&oe=6736C353',
					},
					body: { text: 'sample body 2', example: [] },
					buttons: [{ type: 'QUICK_REPLY', text: 'test 2' }],
				},
				{
					header: {
						format: 'IMAGE',
						example:
							'https://scontent.whatsapp.net/v/t61.29466-34/417678085_1907693496404171_4670733992245415781_n.jpg?ccb=1-7&_nc_sid=a80384&_nc_ohc=eA6a7ingUfoQ7kNvgF2I98q&_nc_ht=scontent.whatsapp.net&edm=AH51TzQEAAAA&_nc_gid=AnaJsX6uZum4NOL3you1z2G&oh=01_Q5AaIIjJRNgNHbNCAVJzLhOoQMQTbc2u6tjGJ76FAZLGkj0n&oe=6736B260',
					},
					body: { text: 'sample body 3', example: [] },
					buttons: [{ type: 'QUICK_REPLY', text: 'test 3' }],
				},
			],
		},
	},
	{
		id: '853831216850857',
		name: 'pv_linkedin_facebook_links_message',
		status: 'APPROVED',
		category: 'MARKETING',
		header: {
			format: 'IMAGE',
			example:
				'https://scontent.whatsapp.net/v/t61.29466-34/459095902_853831223517523_6617838058198772727_n.png?ccb=1-7&_nc_sid=8b1bef&_nc_ohc=0MEbvUuDsg4Q7kNvgHJa6jx&_nc_ht=scontent.whatsapp.net&edm=AH51TzQEAAAA&_nc_gid=AnaJsX6uZum4NOL3you1z2G&oh=01_Q5AaIJrqr6vR_xDi26BE5tShNw5-vOJa2ymYUnQBdYr4PT02&oe=6736D798',
		},
		body: {
			text: 'Lets connect on Social Media also.\n\nPlease click on the button below to connect.\n\n👇👇👇👇',
			example: [],
		},
		buttons: [
			{ type: 'URL', text: 'Linkedin', url: 'https://www.linkedin.com/in/coachprashantvarma/' },
			{ type: 'URL', text: 'Facebook', url: 'https://www.facebook.com/prashaant.varma' },
		],
	},
	{
		id: '560793779628355',
		name: 'sapin40549',
		status: 'REJECTED',
		category: 'MARKETING',
		body: { text: 'qwertyui {{1}}', example: ['asda'] },
		carousel: {
			cards: [
				{
					header: {
						format: 'IMAGE',
						example:
							'https://scontent.whatsapp.net/v/t61.29466-34/442076712_1572018203737367_1757209097769204219_n.jpg?ccb=1-7&_nc_sid=a80384&_nc_ohc=6vrXMmVaUlEQ7kNvgFsmyGP&_nc_ht=scontent.whatsapp.net&edm=AH51TzQEAAAA&_nc_gid=AnaJsX6uZum4NOL3you1z2G&oh=01_Q5AaIPCWtZFKBW4AN-nqNGlEqedFzlT9vyip7WKRCgOkv5ec&oe=6736C174',
					},
					body: { text: 'qwrtyuiop {{1}}', example: ['sdasd'] },
					buttons: [
						{ type: 'QUICK_REPLY', text: 'Hello' },
						{ type: 'QUICK_REPLY', text: 'Hello 2' },
					],
				},
				{
					header: {
						format: 'IMAGE',
						example:
							'https://scontent.whatsapp.net/v/t61.29466-34/456049695_868225658746647_2348372313416957380_n.jpg?ccb=1-7&_nc_sid=a80384&_nc_ohc=i-uhB2yHluYQ7kNvgEp7UuG&_nc_ht=scontent.whatsapp.net&edm=AH51TzQEAAAA&_nc_gid=AnaJsX6uZum4NOL3you1z2G&oh=01_Q5AaIMPHV2DPi_JI3eRwZ9y1rXlG89lQLH6Nsoczl9AV8IvR&oe=6736DA85',
					},
					body: { text: 'asdfghjkl {{1}}', example: ['v fgs'] },
					buttons: [
						{ type: 'QUICK_REPLY', text: 'Hello 3' },
						{ type: 'QUICK_REPLY', text: 'Hello 4' },
					],
				},
			],
		},
	},
	{
		id: '1547477319537802',
		name: 'referral_partner_survey',
		status: 'APPROVED',
		category: 'MARKETING',
		body: {
			text: 'Good Morning BNI {{1}} {{2}} {{3}},\n\nThis is Prashant Varma from BNI Athena, Delhi South.\n\nSaw your profile some time back on BNI Connect.\n\nI recieved an enquiry for Digital Marketing Services in {{4}}\n\nDo you do Digital Marketing.  \n\nKindly confirm 👇',
			example: ['First Name', 'Middle Name', 'Last Name', 'City Name'],
		},
		buttons: [{ type: 'QUICK_REPLY', text: 'I Do Digital Marketing' }],
	},
	{
		id: '1030943261773894',
		name: 'utility_test_message',
		status: 'APPROVED',
		category: 'UTILITY',
		body: { text: 'You received a new notification, {{1}}', example: ['Name'] },
		buttons: [
			{ type: 'QUICK_REPLY', text: 'Yes' },
			{ type: 'QUICK_REPLY', text: 'No' },
		],
	},
	{
		id: '1747181659355758',
		name: 'prashant_real_estate_consultant',
		status: 'APPROVED',
		category: 'MARKETING',
		header: { format: 'TEXT', text: 'Are you a Real Estate Consultant', example: [] },
		body: {
			text: 'Are you a {{1}} {{2}} Based Real Estate Consultant ?',
			example: ['South', 'Delhi'],
		},
		buttons: [
			{ type: 'QUICK_REPLY', text: 'Yes I am in South Delhi' },
			{ type: 'QUICK_REPLY', text: 'No I am Not in South Delh' },
		],
	},
	{
		id: '3369298416697493',
		name: 'propmatch_plot_requirement',
		status: 'APPROVED',
		category: 'MARKETING',
		body: {
			text: 'Hi ,\n\nLooking for a plot or kothi in the following colony for a client.\n\nColony - {{1}} \nSize - {{2}}\n\nKindly confirm if you have something similar available',
			example: ['Hauz Khas / Green Park / Safdarjung Enclave', '200 - 300 Sqyd'],
		},
		footer: { text: 'www.propmatch.in' },
		buttons: [
			{ type: 'QUICK_REPLY', text: 'Plot Available 00001' },
			{ type: 'QUICK_REPLY', text: 'Not Available' },
		],
	},
	{
		id: '823852523056553',
		name: 'task_wautopilot_today_overview',
		status: 'APPROVED',
		category: 'UTILITY',
		body: {
			text: 'Dear {{1}},\n\n{{2}} has updated the status of the task to *{{3}}*.\n\n*Remarks* - {{4}}\n\nHere are the task details:\n*Category* - {{5}}\n*Task* - {{6}}\n*Due Date* - {{7}}\n*Priority* - {{8}}',
			example: [
				'Prashant',
				'Prashant',
				'In Progress',
				'Working on this task',
				'Accounts',
				'Task 1',
				'05-Jul-24 10:00 AM',
				'High',
			],
		},
		footer: { text: 'This is a notification generated by task.wautopilot.com' },
		buttons: [
			{
				type: 'URL',
				text: 'Open Task',
				url: 'https://task.wautopilot.com/organizations{{1}}',
				example: ['task-id-1'],
			},
		],
	},
	{
		id: '950356093128522',
		name: 'lead_notification',
		status: 'APPROVED',
		category: 'MARKETING',
		header: { format: 'TEXT', text: 'Notification from Save My V Card', example: [] },
		body: {
			text: 'Hi {{1}},\n\nThe following person has downloaded your contact card.\n\n*Name*: {{2}}\n*Contact Number*: {{3}}\n*Message Received*:  {{4}}\n\nRegards,\nSaveMyVCard',
			example: ['Prashant', 'Manzar', '919718793635', 'Contact Card for Prashant Varma'],
		},
		buttons: [{ type: 'QUICK_REPLY', text: 'Get Contact Card' }],
	},
	{
		id: '7846637745396362',
		name: 'send_callback_button',
		status: 'APPROVED',
		category: 'MARKETING',
		header: { format: 'TEXT', text: 'CALL BACK BUTTON TESTING', example: [] },
		body: { text: 'Hi,\n\nThis is just to check the callback button on whatsapp.', example: [] },
		buttons: [{ type: 'VOICE_CALL', text: 'Get in touch' }],
	},
	{
		id: '377289165329696',
		name: 'whatsapp_calling_butoon_testing',
		status: 'APPROVED',
		category: 'MARKETING',
		body: { text: 'whatsapp call testing from button', example: [] },
		buttons: [{ type: 'VOICE_CALL', text: 'Whatsapp Call' }],
	},
	{
		id: '750640087231581',
		name: 'bni_requirement',
		status: 'APPROVED',
		category: 'MARKETING',
		body: {
			text: 'Hi {{1}} ,\n\n{{2}}.\n\nKindly let me know if you deal in it or know another BNI member. \n\nRegards,\nPrashant Varma',
			example: ['Name', 'Specific Ask'],
		},
		buttons: [
			{ type: 'QUICK_REPLY', text: 'I deal in this' },
			{ type: 'QUICK_REPLY', text: "I don't deal in this" },
		],
	},
	{
		id: '780197390878909',
		name: 'bni_bniconnect_connection_request',
		status: 'APPROVED',
		category: 'MARKETING',
		body: {
			text: '*Good Morning BNI* {{1}} ,\n\nSent you request on your BNIConnect Profile few days back , please accept it . \n\nAlso wanted to know the best way to stay connected with you .\n\nRegards,\nName - Prashant Varma\nCategory - Performance Coach\nUSP - Helping Businesses grow with the power of Whatsapp\nChapter - BNI Athena\nRegion - Delhi South',
			example: ['Name'],
		},
		buttons: [
			{ type: 'QUICK_REPLY', text: 'Whatsapp' },
			{ type: 'QUICK_REPLY', text: 'Connect on Linkedin' },
			{ type: 'QUICK_REPLY', text: 'I have left BNI' },
		],
	},
	{
		id: '1144349926608624',
		name: 'bni_group_joining_message1',
		status: 'APPROVED',
		category: 'MARKETING',
		body: {
			text: 'Hi {{1}} ,\n\nBased on your request here is the group link based on your business address listed.\n\n{{2}}\n\nIf the above address is correct.\n\nPlease join Nearby Business Network Group  {{3}}',
			example: ['Name', 'address', 'link'],
		},
	},
	{
		id: '724318373199783',
		name: 'mar_bni_pincode_message',
		status: 'APPROVED',
		category: 'MARKETING',
		body: {
			text: 'Good Morning BNI {{1}} ,\n\nWhile going through BNIConnect a few days ago, I saw your office is in {{2}} .\n\nI visit {{2}} regularly, and would like to do 1-2-1 when I visit next time .\n\nPlease share your *Google Location of your Business* .\n\nRegards,\nPrashant Varma\nPerformance Coach\nBNI Athena, Delhi South',
			example: ['Name', 'Colony'],
		},
		buttons: [
			{ type: 'QUICK_REPLY', text: "Let's Connect" },
			{ type: 'QUICK_REPLY', text: 'I will connect later' },
		],
	},
];

export default async function Layout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	// const templates = (await TemplateService.listTemplates())!;
	const medias = await MediaService.getMedias()!;

	return (
		<Suspense fallback={<Loading />}>
			<section>
				<TemplatesProvider data={templates}>
					<MediaProvider data={medias}>{children}</MediaProvider>
				</TemplatesProvider>
			</section>
		</Suspense>
	);
}
